// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtEnksCWF6_6ZoJP-Qi7M8gijTm-uB9RU',
    appId: '1:841137183761:web:89ecda4672a10d103fa5b0',
    messagingSenderId: '841137183761',
    projectId: 'alu-startup-hub',
    authDomain: 'alu-startup-hub.firebaseapp.com',
    storageBucket: 'alu-startup-hub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu7ULKKXV717RN0UCKR2IArDKBF4Gdf0E',
    appId: '1:841137183761:android:ded470f5803f3cee3fa5b0',
    messagingSenderId: '841137183761',
    projectId: 'alu-startup-hub',
    storageBucket: 'alu-startup-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNVupwIFsSlRl-BP8vTb-Ip7nri_tHmUA',
    appId: '1:841137183761:ios:7f1d617b6789e97a3fa5b0',
    messagingSenderId: '841137183761',
    projectId: 'alu-startup-hub',
    storageBucket: 'alu-startup-hub.firebasestorage.app',
    iosBundleId: 'com.alu.aluStartupHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNVupwIFsSlRl-BP8vTb-Ip7nri_tHmUA',
    appId: '1:841137183761:ios:7f1d617b6789e97a3fa5b0',
    messagingSenderId: '841137183761',
    projectId: 'alu-startup-hub',
    storageBucket: 'alu-startup-hub.firebasestorage.app',
    iosBundleId: 'com.alu.aluStartupHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtEnksCWF6_6ZoJP-Qi7M8gijTm-uB9RU',
    appId: '1:841137183761:web:78ab0b94ea62356e3fa5b0',
    messagingSenderId: '841137183761',
    projectId: 'alu-startup-hub',
    authDomain: 'alu-startup-hub.firebaseapp.com',
    storageBucket: 'alu-startup-hub.firebasestorage.app',
  );
}
